"use server";

import { asc, eq, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { getDb } from "@/db";
import { exercises, templateExercises, workoutTemplates } from "@/db/schema";
import { requireSession } from "@/lib/auth";
import { exerciseSchema, profileSchema, templateSchema } from "@/lib/validation";
import { users } from "@/db/schema";

const result = (error?: unknown) => error ? { success: false as const, error: error instanceof Error ? error.message : "That change could not be saved." } : { success: true as const };

export async function createTemplate(input: unknown) { try { await requireSession(); const parsed = templateSchema.parse(input); const db = getDb(); const positions = await db.select({ position: workoutTemplates.position }).from(workoutTemplates).orderBy(asc(workoutTemplates.position)); const position = (positions.at(-1)?.position ?? -1) + 1; await db.insert(workoutTemplates).values({ name: parsed.name, position }); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function renameTemplate(id: string, input: unknown) { try { await requireSession(); const parsed = templateSchema.parse(input); await getDb().update(workoutTemplates).set({ name: parsed.name, updatedAt: new Date() }).where(eq(workoutTemplates.id, id)); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function deleteTemplate(id: string) { try { await requireSession(); await getDb().delete(workoutTemplates).where(eq(workoutTemplates.id, id)); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function moveTemplate(id: string, direction: "up" | "down") { try { await requireSession(); const db = getDb(); const list = await db.select().from(workoutTemplates).orderBy(asc(workoutTemplates.position)); const index = list.findIndex((template) => template.id === id); const nextIndex = direction === "up" ? index - 1 : index + 1; if (index < 0 || !list[nextIndex]) return result(); const reordered = [...list]; [reordered[index], reordered[nextIndex]] = [reordered[nextIndex], reordered[index]]; for (let position = 0; position < reordered.length; position += 1) await db.update(workoutTemplates).set({ position: -(position + 1) }).where(eq(workoutTemplates.id, reordered[position].id)); for (let position = 0; position < reordered.length; position += 1) await db.update(workoutTemplates).set({ position, updatedAt: new Date() }).where(eq(workoutTemplates.id, reordered[position].id)); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function addExerciseToTemplate(templateId: string, exerciseId: string) { try { await requireSession(); const db = getDb(); const last = await db.select({ orderIndex: templateExercises.orderIndex }).from(templateExercises).where(eq(templateExercises.templateId, templateId)).orderBy(sql`${templateExercises.orderIndex} desc`).limit(1); await db.insert(templateExercises).values({ templateId, exerciseId, orderIndex: (last[0]?.orderIndex ?? -1) + 1, targetSets: 3, targetReps: 8 }); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function removeExerciseFromTemplate(id: string) { try { await requireSession(); await getDb().delete(templateExercises).where(eq(templateExercises.id, id)); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function createExercise(input: unknown) { try { await requireSession(); const parsed = exerciseSchema.parse(input); await getDb().insert(exercises).values(parsed); revalidatePath("/library"); return result(); } catch (error) { return result(error); } }
export async function editExercise(id: string, input: unknown) { try { await requireSession(); const parsed = exerciseSchema.parse(input); await getDb().update(exercises).set({ ...parsed, updatedAt: new Date() }).where(eq(exercises.id, id)); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
export async function archiveExercise(id: string, archived: boolean) { try { await requireSession(); await getDb().update(exercises).set({ archived, updatedAt: new Date() }).where(eq(exercises.id, id)); revalidatePath("/library"); return result(); } catch (error) { return result(error); } }
export async function saveProfile(input: unknown) { try { const ownerId = await requireSession(); const parsed = profileSchema.parse(input); await getDb().update(users).set({ heightCm: parsed.heightCm, preferredUnit: parsed.preferredUnit, updatedAt: new Date() }).where(eq(users.id, ownerId)); revalidatePath("/library"); revalidatePath("/today"); return result(); } catch (error) { return result(error); } }
