/**
 * Localization strings for all 11 supported languages.
 *
 * Direct port of the `Resources/*.lproj/Localizable.strings` files.
 */

export type Locale =
  | 'en'
  | 'tr'
  | 'de'
  | 'es'
  | 'fr'
  | 'ja'
  | 'ko'
  | 'zh-Hans'
  | 'ar'
  | 'pt-BR'
  | 'ru';

export const LOCALES: readonly Locale[] = [
  'en',
  'tr',
  'de',
  'es',
  'fr',
  'ja',
  'ko',
  'zh-Hans',
  'ar',
  'pt-BR',
  'ru',
];

/** Maps a BCP-47-style language tag to a supported locale (best effort). */
export function normalizeLocale(tag: string): Locale {
  const lower = tag.toLowerCase();
  const normalized = lower.replace('_', '-');
  if (normalized === 'zh-hans' || normalized === 'zh-cn' || normalized === 'zh') {
    return 'zh-Hans';
  }
  if (normalized === 'pt-br') return 'pt-BR';
  if (normalized === 'pt' || normalized === 'pt-pt') return 'pt-BR';
  if ((LOCALES as readonly string[]).includes(normalized)) {
    return normalized as Locale;
  }
  if (normalized.startsWith('en')) return 'en';
  if (normalized.startsWith('tr')) return 'tr';
  if (normalized.startsWith('de')) return 'de';
  if (normalized.startsWith('es')) return 'es';
  if (normalized.startsWith('fr')) return 'fr';
  if (normalized.startsWith('ja')) return 'ja';
  if (normalized.startsWith('ko')) return 'ko';
  if (normalized.startsWith('ar')) return 'ar';
  if (normalized.startsWith('ru')) return 'ru';
  return 'en';
}

/** The current locale, detected from `navigator.language` or the browser setting. */
export function currentLocale(): Locale {
  if (typeof navigator !== 'undefined' && navigator.language) {
    return normalizeLocale(navigator.language);
  }
  return 'en';
}

const en = {
  'muscle.abs': 'Abs',
  'muscle.adductors': 'Adductors',
  'muscle.ankles': 'Ankles',
  'muscle.biceps': 'Biceps',
  'muscle.calves': 'Calves',
  'muscle.chest': 'Chest',
  'muscle.deltoids': 'Deltoids',
  'muscle.feet': 'Feet',
  'muscle.forearm': 'Forearm',
  'muscle.gluteal': 'Gluteal',
  'muscle.hamstring': 'Hamstring',
  'muscle.hands': 'Hands',
  'muscle.head': 'Head',
  'muscle.knees': 'Knees',
  'muscle.lowerBack': 'Lower Back',
  'muscle.neck': 'Neck',
  'muscle.obliques': 'Obliques',
  'muscle.quadriceps': 'Quadriceps',
  'muscle.tibialis': 'Tibialis',
  'muscle.trapezius': 'Trapezius',
  'muscle.triceps': 'Triceps',
  'muscle.upperBack': 'Upper Back',
  'muscle.rotatorCuff': 'Rotator Cuff',
  'muscle.hipFlexors': 'Hip Flexors',
  'muscle.serratus': 'Serratus',
  'muscle.rhomboids': 'Rhomboids',
  'muscle.upperChest': 'Upper Chest',
  'muscle.lowerChest': 'Lower Chest',
  'muscle.innerQuad': 'Inner Quad',
  'muscle.outerQuad': 'Outer Quad',
  'muscle.upperAbs': 'Upper Abs',
  'muscle.lowerAbs': 'Lower Abs',
  'muscle.frontDeltoid': 'Front Deltoid',
  'muscle.rearDeltoid': 'Rear Deltoid',
  'muscle.upperTrapezius': 'Upper Trapezius',
  'muscle.lowerTrapezius': 'Lower Trapezius',
  'side.left': 'Left',
  'side.right': 'Right',
  'side.both': 'Both',
  'bodySide.front': 'Front',
  'bodySide.back': 'Back',
  'gender.male': 'Male',
  'gender.female': 'Female',
  'accessibility.selected': 'Selected',
  'accessibility.notSelected': 'Not selected',
  'accessibility.hint.tap': 'Double tap to select',
  'accessibility.hint.longPress': 'Long press for details',
  'accessibility.bodyMap': 'Body muscle map',
  'accessibility.muscleRegion': 'Muscle region',
  'accessibility.heatmapLegend': 'Heatmap intensity legend',
  'legend.low': 'Low',
  'legend.high': 'High',
};

const tr: Record<string, string> = {
  'muscle.abs': 'Karın Kası',
  'muscle.adductors': 'Adduktorlar',
  'muscle.ankles': 'Ayak Bilekleri',
  'muscle.biceps': 'Biseps',
  'muscle.calves': 'Baldırlar',
  'muscle.chest': 'Göğüs',
  'muscle.deltoids': 'Deltoidler',
  'muscle.feet': 'Ayaklar',
  'muscle.forearm': 'Ön Kol',
  'muscle.gluteal': 'Kalça Kası',
  'muscle.hamstring': 'Arka Bacak',
  'muscle.hands': 'Eller',
  'muscle.head': 'Baş',
  'muscle.knees': 'Dizler',
  'muscle.lowerBack': 'Alt Sırt',
  'muscle.neck': 'Boyun',
  'muscle.obliques': 'Oblikler',
  'muscle.quadriceps': 'Kuadriseps',
  'muscle.tibialis': 'Ön Baldır',
  'muscle.trapezius': 'Trapez',
  'muscle.triceps': 'Triseps',
  'muscle.upperBack': 'Üst Sırt',
  'muscle.rotatorCuff': 'Rotator Manşet',
  'muscle.hipFlexors': 'Kalça Fleksörleri',
  'muscle.serratus': 'Serratus',
  'muscle.rhomboids': 'Rhomboidler',
  'muscle.upperChest': 'Üst Göğüs',
  'muscle.lowerChest': 'Alt Göğüs',
  'muscle.innerQuad': 'İç Kuadriseps',
  'muscle.outerQuad': 'Dış Kuadriseps',
  'muscle.upperAbs': 'Üst Karın',
  'muscle.lowerAbs': 'Alt Karın',
  'muscle.frontDeltoid': 'Ön Deltoid',
  'muscle.rearDeltoid': 'Arka Deltoid',
  'muscle.upperTrapezius': 'Üst Trapez',
  'muscle.lowerTrapezius': 'Alt Trapez',
  'side.left': 'Sol',
  'side.right': 'Sağ',
  'side.both': 'Her İki Taraf',
  'bodySide.front': 'Ön',
  'bodySide.back': 'Arka',
  'gender.male': 'Erkek',
  'gender.female': 'Kadın',
  'accessibility.selected': 'Seçili',
  'accessibility.notSelected': 'Seçili değil',
  'accessibility.hint.tap': 'Seçmek için çift dokunun',
  'accessibility.hint.longPress': 'Detaylar için uzun basın',
  'accessibility.bodyMap': 'Vücut kas haritası',
  'accessibility.muscleRegion': 'Kas bölgesi',
  'accessibility.heatmapLegend': 'Isı haritası yoğunluk göstergesi',
  'legend.low': 'Düşük',
  'legend.high': 'Yüksek',
};

const de: Record<string, string> = {
  'muscle.abs': 'Bauchmuskeln',
  'muscle.adductors': 'Adduktoren',
  'muscle.ankles': 'Knöchel',
  'muscle.biceps': 'Bizeps',
  'muscle.calves': 'Waden',
  'muscle.chest': 'Brust',
  'muscle.deltoids': 'Deltamuskeln',
  'muscle.feet': 'Füße',
  'muscle.forearm': 'Unterarm',
  'muscle.gluteal': 'Gesäßmuskel',
  'muscle.hamstring': 'Oberschenkelrückseite',
  'muscle.hands': 'Hände',
  'muscle.head': 'Kopf',
  'muscle.knees': 'Knie',
  'muscle.lowerBack': 'Unterer Rücken',
  'muscle.neck': 'Nacken',
  'muscle.obliques': 'Schräge Bauchmuskeln',
  'muscle.quadriceps': 'Quadrizeps',
  'muscle.tibialis': 'Schienbeinmuskel',
  'muscle.trapezius': 'Trapezmuskel',
  'muscle.triceps': 'Trizeps',
  'muscle.upperBack': 'Oberer Rücken',
  'muscle.rotatorCuff': 'Rotatorenmanschette',
  'muscle.hipFlexors': 'Hüftbeuger',
  'muscle.serratus': 'Sägemuskel',
  'muscle.rhomboids': 'Rautenmuskeln',
  'muscle.upperChest': 'Obere Brust',
  'muscle.lowerChest': 'Untere Brust',
  'muscle.innerQuad': 'Innerer Quadrizeps',
  'muscle.outerQuad': 'Äußerer Quadrizeps',
  'muscle.upperAbs': 'Obere Bauchmuskeln',
  'muscle.lowerAbs': 'Untere Bauchmuskeln',
  'muscle.frontDeltoid': 'Vorderer Deltamuskel',
  'muscle.rearDeltoid': 'Hinterer Deltamuskel',
  'muscle.upperTrapezius': 'Oberer Trapezmuskel',
  'muscle.lowerTrapezius': 'Unterer Trapezmuskel',
  'side.left': 'Links',
  'side.right': 'Rechts',
  'side.both': 'Beide',
  'bodySide.front': 'Vorderseite',
  'bodySide.back': 'Rückseite',
  'gender.male': 'Männlich',
  'gender.female': 'Weiblich',
  'accessibility.selected': 'Ausgewählt',
  'accessibility.notSelected': 'Nicht ausgewählt',
  'accessibility.hint.tap': 'Zum Auswählen doppeltippen',
  'accessibility.hint.longPress': 'Für Details lange drücken',
  'accessibility.bodyMap': 'Körper-Muskelkarte',
  'accessibility.muscleRegion': 'Muskelbereich',
  'accessibility.heatmapLegend': 'Heatmap-Intensitätslegende',
  'legend.low': 'Niedrig',
  'legend.high': 'Hoch',
};

const es: Record<string, string> = {
  'muscle.abs': 'Abdominales',
  'muscle.adductors': 'Aductores',
  'muscle.ankles': 'Tobillos',
  'muscle.biceps': 'Bíceps',
  'muscle.calves': 'Pantorrillas',
  'muscle.chest': 'Pecho',
  'muscle.deltoids': 'Deltoides',
  'muscle.feet': 'Pies',
  'muscle.forearm': 'Antebrazo',
  'muscle.gluteal': 'Glúteos',
  'muscle.hamstring': 'Isquiotibiales',
  'muscle.hands': 'Manos',
  'muscle.head': 'Cabeza',
  'muscle.knees': 'Rodillas',
  'muscle.lowerBack': 'Espalda Baja',
  'muscle.neck': 'Cuello',
  'muscle.obliques': 'Oblicuos',
  'muscle.quadriceps': 'Cuádriceps',
  'muscle.tibialis': 'Tibial',
  'muscle.trapezius': 'Trapecio',
  'muscle.triceps': 'Tríceps',
  'muscle.upperBack': 'Espalda Alta',
  'muscle.rotatorCuff': 'Manguito Rotador',
  'muscle.hipFlexors': 'Flexores de Cadera',
  'muscle.serratus': 'Serrato',
  'muscle.rhomboids': 'Romboides',
  'muscle.upperChest': 'Pecho Superior',
  'muscle.lowerChest': 'Pecho Inferior',
  'muscle.innerQuad': 'Cuádriceps Interno',
  'muscle.outerQuad': 'Cuádriceps Externo',
  'muscle.upperAbs': 'Abdominales Superiores',
  'muscle.lowerAbs': 'Abdominales Inferiores',
  'muscle.frontDeltoid': 'Deltoides Frontal',
  'muscle.rearDeltoid': 'Deltoides Posterior',
  'muscle.upperTrapezius': 'Trapecio Superior',
  'muscle.lowerTrapezius': 'Trapecio Inferior',
  'side.left': 'Izquierda',
  'side.right': 'Derecha',
  'side.both': 'Ambos',
  'bodySide.front': 'Frente',
  'bodySide.back': 'Espalda',
  'gender.male': 'Masculino',
  'gender.female': 'Femenino',
  'accessibility.selected': 'Seleccionado',
  'accessibility.notSelected': 'No seleccionado',
  'accessibility.hint.tap': 'Toca dos veces para seleccionar',
  'accessibility.hint.longPress': 'Mantén presionado para detalles',
  'accessibility.bodyMap': 'Mapa muscular del cuerpo',
  'accessibility.muscleRegion': 'Región muscular',
  'accessibility.heatmapLegend': 'Leyenda de intensidad del mapa de calor',
  'legend.low': 'Bajo',
  'legend.high': 'Alto',
};

const fr: Record<string, string> = {
  'muscle.abs': 'Abdominaux',
  'muscle.adductors': 'Adducteurs',
  'muscle.ankles': 'Chevilles',
  'muscle.biceps': 'Biceps',
  'muscle.calves': 'Mollets',
  'muscle.chest': 'Poitrine',
  'muscle.deltoids': 'Deltoïdes',
  'muscle.feet': 'Pieds',
  'muscle.forearm': 'Avant-bras',
  'muscle.gluteal': 'Fessiers',
  'muscle.hamstring': 'Ischio-jambiers',
  'muscle.hands': 'Mains',
  'muscle.head': 'Tête',
  'muscle.knees': 'Genoux',
  'muscle.lowerBack': 'Bas du dos',
  'muscle.neck': 'Cou',
  'muscle.obliques': 'Obliques',
  'muscle.quadriceps': 'Quadriceps',
  'muscle.tibialis': 'Tibial',
  'muscle.trapezius': 'Trapèze',
  'muscle.triceps': 'Triceps',
  'muscle.upperBack': 'Haut du dos',
  'muscle.rotatorCuff': 'Coiffe des rotateurs',
  'muscle.hipFlexors': 'Fléchisseurs de hanche',
  'muscle.serratus': 'Dentelé',
  'muscle.rhomboids': 'Rhomboïdes',
  'muscle.upperChest': 'Haut de poitrine',
  'muscle.lowerChest': 'Bas de poitrine',
  'muscle.innerQuad': 'Quadriceps interne',
  'muscle.outerQuad': 'Quadriceps externe',
  'muscle.upperAbs': 'Abdominaux supérieurs',
  'muscle.lowerAbs': 'Abdominaux inférieurs',
  'muscle.frontDeltoid': 'Deltoïde antérieur',
  'muscle.rearDeltoid': 'Deltoïde postérieur',
  'muscle.upperTrapezius': 'Trapèze supérieur',
  'muscle.lowerTrapezius': 'Trapèze inférieur',
  'side.left': 'Gauche',
  'side.right': 'Droite',
  'side.both': 'Les deux',
  'bodySide.front': 'Avant',
  'bodySide.back': 'Arrière',
  'gender.male': 'Masculin',
  'gender.female': 'Féminin',
  'accessibility.selected': 'Sélectionné',
  'accessibility.notSelected': 'Non sélectionné',
  'accessibility.hint.tap': 'Touchez deux fois pour sélectionner',
  'accessibility.hint.longPress': 'Appui long pour les détails',
  'accessibility.bodyMap': 'Carte musculaire du corps',
  'accessibility.muscleRegion': 'Région musculaire',
  'accessibility.heatmapLegend': "Légende d'intensité de la carte thermique",
  'legend.low': 'Faible',
  'legend.high': 'Élevé',
};

const ja: Record<string, string> = {
  'muscle.abs': '腹筋',
  'muscle.adductors': '内転筋',
  'muscle.ankles': '足首',
  'muscle.biceps': '上腕二頭筋',
  'muscle.calves': 'ふくらはぎ',
  'muscle.chest': '胸筋',
  'muscle.deltoids': '三角筋',
  'muscle.feet': '足',
  'muscle.forearm': '前腕',
  'muscle.gluteal': '臀筋',
  'muscle.hamstring': 'ハムストリング',
  'muscle.hands': '手',
  'muscle.head': '頭',
  'muscle.knees': '膝',
  'muscle.lowerBack': '腰',
  'muscle.neck': '首',
  'muscle.obliques': '腹斜筋',
  'muscle.quadriceps': '大腿四頭筋',
  'muscle.tibialis': '前脛骨筋',
  'muscle.trapezius': '僧帽筋',
  'muscle.triceps': '上腕三頭筋',
  'muscle.upperBack': '背中上部',
  'muscle.rotatorCuff': '回旋筋腱板',
  'muscle.hipFlexors': '股関節屈筋',
  'muscle.serratus': '前鋸筋',
  'muscle.rhomboids': '菱形筋',
  'muscle.upperChest': '大胸筋上部',
  'muscle.lowerChest': '大胸筋下部',
  'muscle.innerQuad': '内側広筋',
  'muscle.outerQuad': '外側広筋',
  'muscle.upperAbs': '上腹筋',
  'muscle.lowerAbs': '下腹筋',
  'muscle.frontDeltoid': '三角筋前部',
  'muscle.rearDeltoid': '三角筋後部',
  'muscle.upperTrapezius': '上部僧帽筋',
  'muscle.lowerTrapezius': '下部僧帽筋',
  'side.left': '左',
  'side.right': '右',
  'side.both': '両側',
  'bodySide.front': '前面',
  'bodySide.back': '背面',
  'gender.male': '男性',
  'gender.female': '女性',
  'accessibility.selected': '選択中',
  'accessibility.notSelected': '未選択',
  'accessibility.hint.tap': 'ダブルタップで選択',
  'accessibility.hint.longPress': '長押しで詳細',
  'accessibility.bodyMap': '筋肉マップ',
  'accessibility.muscleRegion': '筋肉部位',
  'accessibility.heatmapLegend': 'ヒートマップ強度の凡例',
  'legend.low': '低',
  'legend.high': '高',
};

const ko: Record<string, string> = {
  'muscle.abs': '복근',
  'muscle.adductors': '내전근',
  'muscle.ankles': '발목',
  'muscle.biceps': '이두근',
  'muscle.calves': '종아리',
  'muscle.chest': '가슴',
  'muscle.deltoids': '삼각근',
  'muscle.feet': '발',
  'muscle.forearm': '전완근',
  'muscle.gluteal': '둔근',
  'muscle.hamstring': '햄스트링',
  'muscle.hands': '손',
  'muscle.head': '머리',
  'muscle.knees': '무릎',
  'muscle.lowerBack': '하부 등',
  'muscle.neck': '목',
  'muscle.obliques': '복사근',
  'muscle.quadriceps': '대퇴사두근',
  'muscle.tibialis': '전경골근',
  'muscle.trapezius': '승모근',
  'muscle.triceps': '삼두근',
  'muscle.upperBack': '상부 등',
  'muscle.rotatorCuff': '회전근개',
  'muscle.hipFlexors': '고관절 굴근',
  'muscle.serratus': '전거근',
  'muscle.rhomboids': '능형근',
  'muscle.upperChest': '상부 가슴',
  'muscle.lowerChest': '하부 가슴',
  'muscle.innerQuad': '내측 대퇴사두근',
  'muscle.outerQuad': '외측 대퇴사두근',
  'muscle.upperAbs': '상부 복근',
  'muscle.lowerAbs': '하부 복근',
  'muscle.frontDeltoid': '전면 삼각근',
  'muscle.rearDeltoid': '후면 삼각근',
  'muscle.upperTrapezius': '상부 승모근',
  'muscle.lowerTrapezius': '하부 승모근',
  'side.left': '왼쪽',
  'side.right': '오른쪽',
  'side.both': '양쪽',
  'bodySide.front': '전면',
  'bodySide.back': '후면',
  'gender.male': '남성',
  'gender.female': '여성',
  'accessibility.selected': '선택됨',
  'accessibility.notSelected': '선택되지 않음',
  'accessibility.hint.tap': '선택하려면 이중 탭',
  'accessibility.hint.longPress': '길게 눌러 상세 보기',
  'accessibility.bodyMap': '신체 근육 지도',
  'accessibility.muscleRegion': '근육 부위',
  'accessibility.heatmapLegend': '히트맵 강도 범례',
  'legend.low': '낮음',
  'legend.high': '높음',
};

const zhHans: Record<string, string> = {
  'muscle.abs': '腹肌',
  'muscle.adductors': '内收肌',
  'muscle.ankles': '脚踝',
  'muscle.biceps': '肱二头肌',
  'muscle.calves': '小腿',
  'muscle.chest': '胸肌',
  'muscle.deltoids': '三角肌',
  'muscle.feet': '脚',
  'muscle.forearm': '前臂',
  'muscle.gluteal': '臀肌',
  'muscle.hamstring': '腘绳肌',
  'muscle.hands': '手',
  'muscle.head': '头',
  'muscle.knees': '膝盖',
  'muscle.lowerBack': '下背',
  'muscle.neck': '颈部',
  'muscle.obliques': '腹外斜肌',
  'muscle.quadriceps': '股四头肌',
  'muscle.tibialis': '胫骨前肌',
  'muscle.trapezius': '斜方肌',
  'muscle.triceps': '肱三头肌',
  'muscle.upperBack': '上背',
  'muscle.rotatorCuff': '肩袖',
  'muscle.hipFlexors': '髋屈肌',
  'muscle.serratus': '前锯肌',
  'muscle.rhomboids': '菱形肌',
  'muscle.upperChest': '上胸',
  'muscle.lowerChest': '下胸',
  'muscle.innerQuad': '股内侧肌',
  'muscle.outerQuad': '股外侧肌',
  'muscle.upperAbs': '上腹肌',
  'muscle.lowerAbs': '下腹肌',
  'muscle.frontDeltoid': '三角肌前束',
  'muscle.rearDeltoid': '三角肌后束',
  'muscle.upperTrapezius': '上斜方肌',
  'muscle.lowerTrapezius': '下斜方肌',
  'side.left': '左',
  'side.right': '右',
  'side.both': '两侧',
  'bodySide.front': '正面',
  'bodySide.back': '背面',
  'gender.male': '男性',
  'gender.female': '女性',
  'accessibility.selected': '已选择',
  'accessibility.notSelected': '未选择',
  'accessibility.hint.tap': '轻点两下以选择',
  'accessibility.hint.longPress': '长按查看详情',
  'accessibility.bodyMap': '身体肌肉图',
  'accessibility.muscleRegion': '肌肉区域',
  'accessibility.heatmapLegend': '热力图强度图例',
  'legend.low': '低',
  'legend.high': '高',
};

const ar: Record<string, string> = {
  'muscle.abs': 'عضلات البطن',
  'muscle.adductors': 'العضلات المقربة',
  'muscle.ankles': 'الكاحل',
  'muscle.biceps': 'العضلة ذات الرأسين',
  'muscle.calves': 'عضلات الساق',
  'muscle.chest': 'الصدر',
  'muscle.deltoids': 'العضلة الدالية',
  'muscle.feet': 'القدمين',
  'muscle.forearm': 'الساعد',
  'muscle.gluteal': 'عضلات الأرداف',
  'muscle.hamstring': 'أوتار الركبة',
  'muscle.hands': 'اليدين',
  'muscle.head': 'الرأس',
  'muscle.knees': 'الركبتين',
  'muscle.lowerBack': 'أسفل الظهر',
  'muscle.neck': 'الرقبة',
  'muscle.obliques': 'العضلات المائلة',
  'muscle.quadriceps': 'العضلة الرباعية',
  'muscle.tibialis': 'العضلة الظنبوبية',
  'muscle.trapezius': 'العضلة شبه المنحرفة',
  'muscle.triceps': 'العضلة ثلاثية الرؤوس',
  'muscle.upperBack': 'أعلى الظهر',
  'muscle.rotatorCuff': 'الكفة المدورة',
  'muscle.hipFlexors': 'عضلات ثني الورك',
  'muscle.serratus': 'العضلة المنشارية',
  'muscle.rhomboids': 'العضلات المعينية',
  'muscle.upperChest': 'الصدر العلوي',
  'muscle.lowerChest': 'الصدر السفلي',
  'muscle.innerQuad': 'الرباعية الداخلية',
  'muscle.outerQuad': 'الرباعية الخارجية',
  'muscle.upperAbs': 'البطن العلوية',
  'muscle.lowerAbs': 'البطن السفلية',
  'muscle.frontDeltoid': 'الدالية الأمامية',
  'muscle.rearDeltoid': 'الدالية الخلفية',
  'muscle.upperTrapezius': 'شبه المنحرفة العلوية',
  'muscle.lowerTrapezius': 'شبه المنحرفة السفلية',
  'side.left': 'يسار',
  'side.right': 'يمين',
  'side.both': 'كلاهما',
  'bodySide.front': 'الأمام',
  'bodySide.back': 'الخلف',
  'gender.male': 'ذكر',
  'gender.female': 'أنثى',
  'accessibility.selected': 'محدد',
  'accessibility.notSelected': 'غير محدد',
  'accessibility.hint.tap': 'انقر مرتين للتحديد',
  'accessibility.hint.longPress': 'اضغط مطولاً للتفاصيل',
  'accessibility.bodyMap': 'خريطة عضلات الجسم',
  'accessibility.muscleRegion': 'منطقة عضلية',
  'accessibility.heatmapLegend': 'مفتاح شدة الخريطة الحرارية',
  'legend.low': 'منخفض',
  'legend.high': 'مرتفع',
};

const ptBr: Record<string, string> = {
  'muscle.abs': 'Abdominais',
  'muscle.adductors': 'Adutores',
  'muscle.ankles': 'Tornozelos',
  'muscle.biceps': 'Bíceps',
  'muscle.calves': 'Panturrilhas',
  'muscle.chest': 'Peito',
  'muscle.deltoids': 'Deltoides',
  'muscle.feet': 'Pés',
  'muscle.forearm': 'Antebraço',
  'muscle.gluteal': 'Glúteos',
  'muscle.hamstring': 'Isquiotibiais',
  'muscle.hands': 'Mãos',
  'muscle.head': 'Cabeça',
  'muscle.knees': 'Joelhos',
  'muscle.lowerBack': 'Lombar',
  'muscle.neck': 'Pescoço',
  'muscle.obliques': 'Oblíquos',
  'muscle.quadriceps': 'Quadríceps',
  'muscle.tibialis': 'Tibial',
  'muscle.trapezius': 'Trapézio',
  'muscle.triceps': 'Tríceps',
  'muscle.upperBack': 'Costas Superior',
  'muscle.rotatorCuff': 'Manguito Rotador',
  'muscle.hipFlexors': 'Flexores do Quadril',
  'muscle.serratus': 'Serrátil',
  'muscle.rhomboids': 'Romboides',
  'muscle.upperChest': 'Peito Superior',
  'muscle.lowerChest': 'Peito Inferior',
  'muscle.innerQuad': 'Quadríceps Interno',
  'muscle.outerQuad': 'Quadríceps Externo',
  'muscle.upperAbs': 'Abdominais Superiores',
  'muscle.lowerAbs': 'Abdominais Inferiores',
  'muscle.frontDeltoid': 'Deltoide Frontal',
  'muscle.rearDeltoid': 'Deltoide Posterior',
  'muscle.upperTrapezius': 'Trapézio Superior',
  'muscle.lowerTrapezius': 'Trapézio Inferior',
  'side.left': 'Esquerda',
  'side.right': 'Direita',
  'side.both': 'Ambos',
  'bodySide.front': 'Frente',
  'bodySide.back': 'Costas',
  'gender.male': 'Masculino',
  'gender.female': 'Feminino',
  'accessibility.selected': 'Selecionado',
  'accessibility.notSelected': 'Não selecionado',
  'accessibility.hint.tap': 'Toque duas vezes para selecionar',
  'accessibility.hint.longPress': 'Pressione e segure para detalhes',
  'accessibility.bodyMap': 'Mapa muscular do corpo',
  'accessibility.muscleRegion': 'Região muscular',
  'accessibility.heatmapLegend': 'Legenda de intensidade do mapa de calor',
  'legend.low': 'Baixo',
  'legend.high': 'Alto',
};

const ru: Record<string, string> = {
  'muscle.abs': 'Пресс',
  'muscle.adductors': 'Аддукторы',
  'muscle.ankles': 'Лодыжки',
  'muscle.biceps': 'Бицепс',
  'muscle.calves': 'Икры',
  'muscle.chest': 'Грудь',
  'muscle.deltoids': 'Дельтовидные',
  'muscle.feet': 'Стопы',
  'muscle.forearm': 'Предплечье',
  'muscle.gluteal': 'Ягодицы',
  'muscle.hamstring': 'Бицепс бедра',
  'muscle.hands': 'Кисти',
  'muscle.head': 'Голова',
  'muscle.knees': 'Колени',
  'muscle.lowerBack': 'Поясница',
  'muscle.neck': 'Шея',
  'muscle.obliques': 'Косые мышцы',
  'muscle.quadriceps': 'Квадрицепс',
  'muscle.tibialis': 'Передняя большеберцовая',
  'muscle.trapezius': 'Трапеция',
  'muscle.triceps': 'Трицепс',
  'muscle.upperBack': 'Верх спины',
  'muscle.rotatorCuff': 'Вращательная манжета',
  'muscle.hipFlexors': 'Сгибатели бедра',
  'muscle.serratus': 'Зубчатая мышца',
  'muscle.rhomboids': 'Ромбовидные',
  'muscle.upperChest': 'Верх груди',
  'muscle.lowerChest': 'Низ груди',
  'muscle.innerQuad': 'Внутренний квадрицепс',
  'muscle.outerQuad': 'Внешний квадрицепс',
  'muscle.upperAbs': 'Верхний пресс',
  'muscle.lowerAbs': 'Нижний пресс',
  'muscle.frontDeltoid': 'Передняя дельта',
  'muscle.rearDeltoid': 'Задняя дельта',
  'muscle.upperTrapezius': 'Верхняя трапеция',
  'muscle.lowerTrapezius': 'Нижняя трапеция',
  'side.left': 'Левая',
  'side.right': 'Правая',
  'side.both': 'Обе стороны',
  'bodySide.front': 'Передняя сторона',
  'bodySide.back': 'Задняя сторона',
  'gender.male': 'Мужское',
  'gender.female': 'Женское',
  'accessibility.selected': 'Выбрано',
  'accessibility.notSelected': 'Не выбрано',
  'accessibility.hint.tap': 'Нажмите дважды для выбора',
  'accessibility.hint.longPress': 'Долгое нажатие для подробностей',
  'accessibility.bodyMap': 'Карта мышц тела',
  'accessibility.muscleRegion': 'Область мышц',
  'accessibility.heatmapLegend': 'Легенда интенсивности тепловой карты',
  'legend.low': 'Низкая',
  'legend.high': 'Высокая',
};

const BUNDLES: Record<Locale, Record<string, string>> = {
  en,
  tr,
  de,
  es,
  fr,
  ja,
  ko,
  'zh-Hans': zhHans,
  ar,
  'pt-BR': ptBr,
  ru,
};

/**
 * Looks up a localized string for a key in the given locale, falling back to
 * English and finally to the key itself.
 */
export function translate(key: string, locale: Locale = 'en'): string {
  const bundle = BUNDLES[locale];
  const value = bundle?.[key];
  if (value !== undefined) return value;
  const fallback = en[key as keyof typeof en];
  return fallback !== undefined ? fallback : key;
}

/** Returns the localized display name for a muscle. */
export function muscleDisplayName(
  muscle: string,
  locale: Locale = 'en'
): string {
  return translate(`muscle.${muscle}`, locale);
}

/** Returns the localized display name for a muscle side. */
export function sideDisplayName(side: string, locale: Locale = 'en'): string {
  return translate(`side.${side}`, locale);
}

/** Returns the localized display name for a body side (front/back). */
export function bodySideDisplayName(side: string, locale: Locale = 'en'): string {
  return translate(`bodySide.${side}`, locale);
}

/** Returns the localized display name for a body gender. */
export function genderDisplayName(gender: string, locale: Locale = 'en'): string {
  return translate(`gender.${gender}`, locale);
}
